### ISSUE TITLE
Silverstripe 4

### ISSUE THREAD

**Issue by derralf** [nblum/silverstripe-geocodefield#3]
Are you planning on making the module compatible with SilverStripe 4?

**Comment by nblum** [comment]
good question. I have not started yet this task.
After a quick code review i think it's not a really big deal. How fast do you need a working solution for v4

**Comment by derralf** [comment]
not fast :) but good to hear.
i've not yet switched to v4. i'm just checking modules I usually use.

**Comment by nblum** [comment]
as expected the effort was not very huge. V4 is now supported.
I welcome feedback
